name: TheEvent580_Plugin
main: fr.thefox580.theevent580.main
version: 1.5.1
api-version: '1.20'
author: TheFox580
description: TheEvent580's Plugin

commands:
  starttp:
    description: Tp after start
    permission: op
  gametp:
    description: Tp after games
    permission: op
  setrp:
      description: Set a rp to a player
      permission: op
  rideplayer:
      description: Ride a player
      permission: op
  points:
    description: Add / removes points to a player
    permission: op
  gamepoints:
    description: Add / removes game points to a player
    permission: op
  totalpoints:
    description: Add / removes total points to a player
    permission: op
  getpoints:
    description: Shows the points of player in arg to commandSender
  getgamepoints:
    description: Shows the points of player in arg to commandSender
  gettotalpoints:
    description: Shows the points of player in arg to commandSender
  setglobalmultiplier:
    description: Sets the point multiplier of the next game
    permission: op
  getglobalmultiplier:
    description: Shows the point multiplier of the next game
  gamemultiplier:
    description: Add / removes game multipler to the player
    permission: op
  timer:
    description: Set the timer mode / time and if it's active or not
    permission: op
  start:
    description: Starts the event
    permission: op
  pronouns:
    description: Changes player's pronouns
  damage:
    description: Toggles damage
    permission: op