name: TheEvent580-Plugin
main: fr.thefox580.theevent580.main
version: 1.4
author: TheFox580
description: TheEvent580's Plugin

commands:
  starttp:
    description: Tp after start
    permission: op
  gametp:
    description: Tp after games
    permission: op
  setrp:
      description: Set a rp to a player
      permission: op
  rideplayer:
      description: Ride a player
      permission: op
