name: TheEvent580_Plugin
main: fr.thefox580.theevent580.main
version: 1.4.3
api-version: '1.20'
author: TheFox580
description: TheEvent580's Plugin

commands:
  starttp:
    description: Tp after start
    permission: op
  gametp:
    description: Tp after games
    permission: op
  setrp:
      description: Set a rp to a player
      permission: op
  rideplayer:
      description: Ride a player
      permission: op
